export const agentsSeed = [
  {
    id: 'seed-agent-operations',
    name: 'Operations Copilot',
    slug: 'operations-copilot',
    description: 'Agente generalista para soporte operativo y consultas de plataforma.',
    instructions: 'Responde con claridad, prioriza acciones concretas y cita limitaciones si faltan datos.',
    status: 'ACTIVE',
    isEnabled: true,
    routingPolicyId: 'seed-policy-openai-main',
    skillIds: ['seed-skill-analysis', 'seed-skill-ops'],
    toolIds: ['seed-tool-status-api'],
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    id: 'seed-agent-local-lab',
    name: 'Local Lab Agent',
    slug: 'local-lab-agent',
    description: 'Agente para pruebas locales con modelos self-hosted.',
    instructions: 'Trabaja con bajo coste, resume hallazgos y mantente estricto con el contexto dado.',
    status: 'ACTIVE',
    isEnabled: true,
    routingPolicyId: 'seed-policy-local-dev',
    skillIds: ['seed-skill-analysis'],
    toolIds: ['seed-tool-local-shell'],
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
  },
];
