export const toolsSeed = [
  {
    id: 'seed-tool-status-api',
    name: 'Status API',
    slug: 'status-api',
    description: 'Tool HTTP para consultar estado de servicios.',
    kind: 'http',
    endpoint: 'https://status.example.com/api/health',
    method: 'GET',
    isEnabled: true,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    id: 'seed-tool-local-shell',
    name: 'Local Shell Tool',
    slug: 'local-shell-tool',
    description: 'Tool conceptual para ejecucion local controlada.',
    kind: 'shell',
    endpoint: null,
    method: null,
    isEnabled: true,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    id: 'seed-tool-ticket-api',
    name: 'Ticket API',
    slug: 'ticket-api',
    description:
      'Tool HTTP para consultar, clasificar y actualizar tickets de soporte.',
    kind: 'http',
    endpoint: 'https://support.example.com/api/tickets',
    method: 'POST',
    isEnabled: true,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    id: 'seed-tool-docs-search',
    name: 'Documentation Search',
    slug: 'documentation-search',
    description: 'Tool HTTP para buscar en documentacion publica e interna.',
    kind: 'http',
    endpoint: 'https://docs.example.com/api/search',
    method: 'GET',
    isEnabled: true,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    id: 'seed-tool-health-checks',
    name: 'Health Checks API',
    slug: 'health-checks-api',
    description:
      'Tool HTTP para revisar health checks, uptime y señales basicas de servicios.',
    kind: 'http',
    endpoint: 'https://status.example.com/api/checks',
    method: 'GET',
    isEnabled: true,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
  },
];
